* description

ScRead is a plugin for Anki SRS.

ScRead (short for Scrutinized Reading) is a set of tools to help reading texts. 
In a nutshell, it ensures that you know all words in the text before
you read it and if not, it helps you to memorize them.

The plugin's name is similar to [[https://ankiweb.net/shared/info/4052460373][Incremental Reading plugin]] as they
both deal with texts but their purposes and methods are different.
While Incremental Reading plugin allows you to memorize pieces of
text after you read it, Scrunitized Reading plugin makes you memorize
everything that you don't know before you read the text.


Usage:
  On the first start you should select menu "Tools -> ScRead -> Init" to
  create decks and auxiliary stuff.

  Suppose you are going to read an article or another piece of text.
  Here is how you deal with it using ScRead:
  
  - Add the text(s)
    Open deck "ScRead::Texts" and add a new note with type "ScRead.Text".
    Field "Text" should contain your text.
    Field "Source" should contain source of the text, like url, article name etc.
    
  - Parse texts
    After you have done adding texts, select menu "Tools -> ScRead -> Parse Texts"
    New cards in deck "ScRead::Words -> Unsorted" will appear.
   
  - Filter unknown words
    Open deck "ScRead::Words -> Unsorted" and hit "Study now".
    The process differs from regular Anki studing.
    For each card you choose one of the following:
    - "Good"  -- if you know the word well and have no need to memorize it
    - "Again" -- otherwise
      This card will go into "ScRead::Words -> Filtered" deck to memorize.
      
  - Supplying cards
    Now you have some words that you don't know. It's time to memorize them.
    Select menu "Tools -> ScRead -> Supply Cards".
    Depending on configuration a translation tool will run against all unknown words.
    New cards in deck "ScRead::Words -> Filtered" will appear.
    
  - Memorizing unknown words
    Open deck "ScRead::Words -> Filtered" and hit "Study now".
    This is a regular Anki studing.

  - Reading the text(s)
    After you have memorized the words well you can proceed to reading the text.
    Select menu "Tools -> ScRead -> Update Estimations".
    This will check for texts with well known words and add them to
    "ScRead::Texts -> Available" deck.
    The rule of thumb: when all the words in filtered deck became "mature"
    the text will be available.


Notes: 
  - You don't have to clear completely "Unsorted" deck before selecting "Supply Cards".
    Both decks can be studied in parallel.
  - Although workflow requires PC version of Anki, the vast amount of work
    can be done on a mobile version.


Configuration:
  Some functions can be replaced, check scread_loader.py for information.
  Deck "ScRead::Words -> Filtered" can be configured as you wish.

  
Limitations:
  - Inserting a big book is not a good idea since it may take a lot of time and space
    in the internal database. 

  - The plugin requres external tools to translate words. The following utilites are supported: 
    - [[http://sdcv.sourceforge.net/][sdcv]]
    - [[http://www.soimort.org/translate-shell/][trans]]
    
  - The plugin is targeted at english texts


Extension:
  Initially, the plugin was designed to be modular, so you can easily add your own functions to
  overcome its limitations. Check files parse.py, translate.py and estimate.py for further info.
    

* roadmap 
  - todo [0/6]
    
    - [ ] link with anki repository
    - [-] menu [3/12]
      - [X] init
      - [X] reset
        
      - [X] parse_texts_all, parse_texts_next_one, parse_texts_next_shortest_one
        - [X] parse_text

      - [ ] mark_words_as_known
      - [ ] mark_words_as_unknown

      - [ ] add_translations_from_all_available_sources
      - [ ] add_translations_from_google_translate
      - [ ] add_translations_from_stardict
      - [ ] add_translations_from_ethymonline
            http://www.etymonline.com/index.php?allowed_in_frame=0&search=overall&searchmode=term 
        - [ ] fetch page
        - [ ] extract data

      - [ ] update_estimations

      - [ ] * delimiter
      - [ ] * shortcuts

    - [ ] description
      
    - [ ] functionality [0/4]
      - [ ] time limit restriction for online services
      - [ ] * soft update for models/decks
      - [ ] tag for ignored
      - [ ] replace sql
        
    - [ ] bugs [0/1]
      - [ ] check: hospitals <-> deteriorate highlighting?

    - [ ] tests
      - [ ] logic


